# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup dependencies
      run: |
       sudo apt-get update --fix-missing
       sudo apt-get install -y build-essential
       sudo apt-get install -y python3
       sudo apt-get install -y libboost-all-dev
       wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
       sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
       sudo apt-get update
       sudo apt-get install -y clang-6.0
       sudo add-apt-repository ppa:ubuntu-toolchain-r/test
       sudo apt install gcc-9 g++-9
       sudo update-alternatives \
       --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 \
       --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
       --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9 \
       --slave /usr/bin/gcov gcov /usr/bin/gcov-9
       sudo update-alternatives \
       --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
